#!/bin/bash

if [ "$1" == "install" ]; then
	python3 -m venv django_venv
	source django_venv/bin/activate
	python3 -m pip install --upgrade pip
	python3 -m pip install -r requirements.txt
	python3 -m pip freeze
	python3 manage.py collectstatic --noinput --clear -v=0
	exit 0
elif [ "$1" == "start" ]; then
	if [ ! -d "django_venv" ]; then
		echo "Virtual environment not found. Run 'run install' first."
		exit 1
	fi
	source django_venv/bin/activate
	python3 manage.py runserver
	python3 manage.py collectstatic --noinput --clear -v=0
	exit 0
elif [ "$1" == "clean" ]; then
	rm -rf django_venv
	rm -rf static
	find . -type d -name "__pycache__" -exec rm -rf {} +
	exit 0
else
	echo "run install | Install requirements"
	echo "run start   | Start the server"
	echo "run clean   | Clean the project"
	exit 0
fi
