# Generated by Django 5.2 on 2025-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(default='', max_length=64, unique=True)),
                ('episode_nb', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(null=True)),
                ('director', models.CharField(default='', max_length=32)),
                ('producer', models.CharField(default='', max_length=128)),
                ('release_date', models.DateField(default='')),
            ],
            options={
                'db_table': 'ex01_movies',
            },
        ),
    ]
