#!/bin/bash

if [ -d "venv" ]; then
	echo "Activating existing virtual environment..."
	source venv/bin/activate
else
	echo "Creating virtual environment..."
	python3 -m venv venv
	source venv/bin/activate
	python3 -m pip install --upgrade pip
	python3 -m pip install -r requirements.txt
	python3 -m pip freeze
fi

python3 manage.py makemigrations
if python3 manage.py showmigrations --plan | grep '\[ \]' >/dev/null 2>&1; then
	python3 manage.py migrate
fi
python3 manage.py collectstatic --noinput --clear -v=0
python3 manage.py runserver
